import type { LightSpec, PrevisAsset, Vec3 } from './types';

const asset = (
  id: string,
  name: string,
  category: string,
  shape: string,
  dimensions: Vec3,
  color: string,
  diagramType = id,
  tags = '',
): PrevisAsset => ({
  id,
  name,
  category,
  shape,
  dimensions,
  color,
  diagramType,
  tags,
});

const fixture = (
  id: string, name: string, category: string, shape: string, dimensions: Vec3, color: string, light: LightSpec | undefined,
  tags = '', extra: Partial<PrevisAsset> = {},
): PrevisAsset => ({ ...asset(id, name, category, shape, dimensions, color, id, tags), ...(light ? { light } : {}), ...extra });

/**
 * Film fixtures, practicals and grip. Output is relative (the inspector shows a dimmer); colour
 * defaults follow the source: 3200 K tungsten, 5600 K daylight and HMI, 2700 K household bulbs.
 */
function lights(): PrevisAsset[] {
  const tungsten = '#ffc58f', daylight = '#fff3e8', household = '#ffb46b', flame = '#ff9a45';
  return [
    fixture('key-light', 'Open-face spot', 'Film lights', 'spot', [0.5, 2.2, 0.5], '#3b4043', { kind: 'spot', intensity: 40, color: tungsten, angle: 40, at: [0.3, 0.93, 0] }, 'key light redhead blonde spotlight'),
    fixture('fresnel', 'Fresnel 1K', 'Film lights', 'fresnel', [0.55, 2.2, 0.5], '#2f3336', { kind: 'spot', intensity: 60, color: tungsten, angle: 30, at: [0.36, 0.92, 0] }, 'tungsten 650 2k arri'),
    fixture('hmi', 'HMI 1.2K', 'Film lights', 'hmi', [0.8, 2.5, 0.7], '#c9ccc8', { kind: 'spot', intensity: 160, color: daylight, angle: 34, at: [0.36, 0.9, 0] }, 'daylight par m18 sun'),
    fixture('dedo', 'Dedolight', 'Film lights', 'par', [0.35, 1.6, 0.35], '#26292b', { kind: 'spot', intensity: 18, color: tungsten, angle: 16, at: [0.38, 0.93, 0] }, 'small spot accent par eye light'),
    fixture('softbox', 'Softbox', 'Film lights', 'softbox', [0.8, 2.1, 0.6], '#2b2e30', { kind: 'area', intensity: 100, color: daylight, at: [0.1, 0.88, 0], size: [0.6, 0.6] }, 'soft key octa'),
    fixture('led-panel', 'LED panel 1×1', 'Film lights', 'panel', [0.6, 2, 0.4], '#2b2e30', { kind: 'area', intensity: 120, color: daylight, at: [0.14, 0.92, 0], size: [0.3, 0.3] }, 'litepanel bicolor workshop light'),
    fixture('skypanel', 'SkyPanel', 'Film lights', 'skypanel', [1.1, 2.1, 0.6], '#34383b', { kind: 'area', intensity: 150, color: daylight, at: [0.12, 0.9, 0], size: [0.65, 0.3] }, 'arri s60 soft'),
    fixture('kino', 'Kino Flo 4-bank', 'Film lights', 'kino', [1.3, 2, 0.6], '#34383b', { kind: 'area', intensity: 110, color: daylight, at: [0.1, 0.9, 0], size: [1.2, 0.3] }, 'fluorescent tube bank'),
    fixture('light-tube', 'Light tube', 'Film lights', 'tube', [0.05, 1.2, 0.05], '#e9eef2', { kind: 'tube', intensity: 320, color: daylight, at: [0, 0.5, 0] }, 'lyssabel astera titan pavotube rod stick led'),
    fixture('ring-light', 'Ring light', 'Film lights', 'ring', [0.5, 1.9, 0.35], '#2b2e30', { kind: 'area', intensity: 90, color: daylight, at: [0.1, 0.87, 0], size: [0.36, 0.36] }, 'beauty'),
    fixture('china-ball', 'China ball', 'Film lights', 'china-ball', [1.3, 2.6, 0.6], '#f3eadb', { kind: 'point', intensity: 25, color: tungsten, at: [0.42, 0.86, 0] }, 'lantern paper chimera boom'),
    fixture('space-light', 'Space light', 'Film lights', 'space-light', [0.9, 1.2, 0.9], '#f1f0ea', { kind: 'point', intensity: 80, color: tungsten, at: [0, 0.2, 0] }, 'overhead skirt ambient', { elevation: 3.5 }),
    fixture('practical-light', 'Bare bulb', 'Practicals', 'bulb', [0.2, 0.3, 0.2], '#f5d99e', { kind: 'point', intensity: 12, color: household, at: [0, 0.6, 0] }, 'lightbulb'),
    fixture('table-lamp', 'Table lamp', 'Practicals', 'lamp', [0.3, 0.5, 0.3], '#d5bd9c', { kind: 'point', intensity: 10, color: household, at: [0, 0.85, 0] }),
    fixture('floor-lamp', 'Floor lamp', 'Practicals', 'lamp', [0.45, 1.65, 0.45], '#d4b58d', { kind: 'point', intensity: 14, color: household, at: [0, 0.86, 0] }),
    fixture('pendant', 'Pendant lamp', 'Practicals', 'pendant', [0.45, 1, 0.45], '#2f3437', { kind: 'point', intensity: 16, color: household, at: [0, 0.08, 0] }, 'ceiling hanging', { elevation: 1.6 }),
    fixture('batten', 'Fluorescent batten', 'Practicals', 'batten', [1.2, 0.08, 0.16], '#dfe3e2', { kind: 'area', intensity: 140, color: '#eef7ff', at: [0, 0, 0], size: [1.15, 0.1], aim: 'down' }, 'ceiling office strip tube', { elevation: 2.7 }),
    fixture('neon-sign', 'Neon sign', 'Practicals', 'neon', [0.9, 0.5, 0.05], '#ff4fa3', { kind: 'area', intensity: 30, color: '#ff4fa3', at: [0, 0.5, 0.6], size: [0.9, 0.5] }, 'bar open sign glow', { elevation: 1.5 }),
    fixture('string-lights', 'String lights', 'Practicals', 'string-lights', [3, 0.4, 0.05], '#2f3234', { kind: 'point', intensity: 5, color: household, at: [0, 0.3, 0] }, 'fairy festoon', { elevation: 2.2 }),
    fixture('candle', 'Candle', 'Practicals', 'candle', [0.07, 0.24, 0.07], '#ece4d2', { kind: 'point', intensity: 1.5, color: flame, at: [0, 0.95, 0] }, 'flame'),
    fixture('street-lamp', 'Street lamp', 'Practicals', 'street-lamp', [0.5, 5, 1.6], '#3a3f42', { kind: 'spot', intensity: 150, color: '#ffc27a', angle: 95, at: [0, 0.97, 0.42], aim: 'down' }, 'sodium lamppost exterior night'),
    fixture('flashlight', 'Flashlight', 'Practicals', 'flashlight', [0.24, 0.05, 0.05], '#2a2d2f', { kind: 'spot', intensity: 20, color: '#fff6e6', angle: 22, at: [0.52, 0.5, 0] }, 'torch handheld', { elevation: 1.2 }),
    fixture('campfire', 'Campfire', 'Practicals', 'campfire', [1, 0.6, 1], '#6c5238', { kind: 'point', intensity: 30, color: flame, at: [0, 0.4, 0] }, 'fire bonfire flame'),
    fixture('torch-standing', 'Standing torch', 'Practicals', 'torch', [0.25, 1.5, 0.25], '#6c5238', { kind: 'point', intensity: 8, color: flame, at: [0, 0.92, 0] }, 'fire flame medieval'),
    fixture('bounce-board', 'Bounce board', 'Grip', 'board', [1.2, 1.8, 0.15], '#e6e2d6', undefined, 'poly reflector white'),
    fixture('flag-cutter', 'Black flag', 'Grip', 'board', [1, 1.8, 0.12], '#292c32', undefined, 'negative fill floppy cutter'),
    fixture('v-flat', 'V-flat', 'Grip', 'v-flat', [1.2, 2.4, 1.2], '#efede6', undefined, 'bounce negative fill studio'),
    fixture('diffusion-frame', 'Diffusion frame', 'Grip', 'diff-frame', [1.8, 2.4, 0.3], '#f4f3ee', undefined, 'butterfly silk 6x6 scrim'),
  ];
}

/** All built-in geometry is generated locally; no remote asset services are required. */
export const previsAssets: PrevisAsset[] = [
  asset(
    'actor-male',
    'Standing person',
    'People',
    'person',
    [0.55, 1.78, 0.4],
    '#729fc1',
    'actor-male',
    'actor character human',
  ),
  {
    ...asset(
      'sitting-actor',
      'Seated person',
      'People',
      'person',
      [0.55, 1.3, 0.75],
      '#b99a80',
    ),
    pose: 'sitting',
  },
  {
    ...asset(
      'walking-actor',
      'Walking person',
      'People',
      'person',
      [0.6, 1.78, 0.65],
      '#8ba993',
      'stunt',
    ),
    pose: 'walking',
  },
  {
    ...asset(
      'lying-actor',
      'Lying person',
      'People',
      'person',
      [0.55, 0.35, 1.78],
      '#ab8ab1',
    ),
    pose: 'lying',
  },
  asset('actor-child', 'Child', 'People', 'person', [0.4, 1.2, 0.3], '#c3a46f'),
  asset(
    'wall',
    'Wall',
    'Architecture',
    'wall',
    [3, 2.8, 0.15],
    '#bcb7ab',
    'wall',
    'room interior partition',
  ),
  asset('cave-wall', 'Cave wall', 'Architecture', 'cave-wall', [3, 3, 0.6], '#80776a', 'cave-wall', 'rock cavern rough stone'),
  asset('cave-pillar', 'Rock pillar', 'Nature', 'rock', [1, 3, 1], '#80776a'),
  asset(
    'door-closed',
    'Door',
    'Architecture',
    'door',
    [0.9, 2.1, 0.15],
    '#8c7460',
  ),
  asset(
    'door-open',
    'Open door',
    'Architecture',
    'open-door',
    [0.9, 2.1, 0.15],
    '#8c7460',
  ),
  asset(
    'window',
    'Window',
    'Architecture',
    'window',
    [1.4, 1.2, 0.15],
    '#839aa4',
  ),
  asset(
    'column',
    'Column',
    'Architecture',
    'column',
    [0.4, 2.8, 0.4],
    '#b6b0a5',
  ),
  asset(
    'stairs',
    'Stairs',
    'Architecture',
    'stairs',
    [1.2, 1.6, 2.4],
    '#a6a19a',
  ),
  asset('platform', 'Platform', 'Architecture', 'box', [3, 0.3, 2], '#898780'),
  asset('archway', 'Archway', 'Architecture', 'arch', [2, 2.8, 0.3], '#c2b9a5'),
  asset(
    'curtain',
    'Curtain',
    'Architecture',
    'curtain',
    [2, 2.5, 0.12],
    '#806879',
  ),
  asset('fence', 'Fence', 'Architecture', 'fence', [3, 1.2, 0.12], '#927d62'),
  asset(
    'table-rect',
    'Dining table',
    'Furniture',
    'table',
    [1.6, 0.76, 0.9],
    '#9d7957',
  ),
  asset(
    'table-round',
    'Round table',
    'Furniture',
    'round-table',
    [1.1, 0.76, 1.1],
    '#9d7957',
  ),
  asset('chair', 'Chair', 'Furniture', 'chair', [0.5, 0.9, 0.5], '#9b876d'),
  asset(
    'armchair',
    'Armchair',
    'Furniture',
    'armchair',
    [0.85, 0.9, 0.9],
    '#788b86',
  ),
  asset('sofa', 'Sofa', 'Furniture', 'sofa', [2.1, 0.9, 0.9], '#81918c'),
  asset('stool', 'Stool', 'Furniture', 'stool', [0.4, 0.65, 0.4], '#a58b68'),
  asset('desk', 'Desk', 'Furniture', 'desk', [1.4, 0.75, 0.65], '#9f8467'),
  asset(
    'bed-double',
    'Double bed',
    'Furniture',
    'bed',
    [1.6, 0.65, 2.1],
    '#c6c0b2',
  ),
  asset(
    'bed-single',
    'Single bed',
    'Furniture',
    'bed',
    [0.9, 0.65, 2.1],
    '#b9b8af',
  ),
  asset(
    'bookshelf',
    'Bookshelf',
    'Furniture',
    'shelf',
    [0.9, 2, 0.35],
    '#987859',
  ),
  asset('cabinet', 'Cabinet', 'Furniture', 'cabinet', [1.2, 1, 0.5], '#8d8070'),
  asset(
    'wardrobe',
    'Wardrobe',
    'Furniture',
    'cabinet',
    [1.5, 2.1, 0.6],
    '#a08e76',
  ),
  asset('rug', 'Rug', 'Furniture', 'rug', [2, 0.015, 3], '#a38b79'),
  ...lights(),
  asset('box-crate', 'Crate', 'Props', 'crate', [0.6, 0.5, 0.6], '#a7885f'),
  asset('barrel', 'Barrel', 'Props', 'barrel', [0.6, 0.9, 0.6], '#9b7251'),
  asset('bottle', 'Bottle', 'Props', 'bottle', [0.09, 0.3, 0.09], '#73917e'),
  asset('cup', 'Cup', 'Props', 'cup', [0.12, 0.12, 0.12], '#c3bbaa'),
  asset('book', 'Book', 'Props', 'box', [0.18, 0.035, 0.25], '#896b62'),
  asset('laptop', 'Laptop', 'Props', 'laptop', [0.35, 0.23, 0.25], '#8c959d'),
  asset(
    'screen-tv',
    'Television',
    'Props',
    'screen',
    [1.2, 0.75, 0.08],
    '#4e5661',
  ),
  asset('mirror', 'Mirror', 'Props', 'screen', [0.65, 1.7, 0.06], '#a1b6bd'),
  asset(
    'suitcase',
    'Suitcase',
    'Props',
    'crate',
    [0.45, 0.65, 0.25],
    '#756b64',
  ),
  asset(
    'potted-plant',
    'Potted plant',
    'Props',
    'plant',
    [0.5, 1, 0.5],
    '#71816a',
  ),
  asset(
    'kitchen-counter',
    'Kitchen counter',
    'Interiors',
    'counter',
    [2, 0.9, 0.6],
    '#b6ada0',
  ),
  asset(
    'kitchen-island',
    'Kitchen island',
    'Interiors',
    'counter',
    [1.8, 0.9, 0.9],
    '#a89f90',
  ),
  asset(
    'fridge',
    'Refrigerator',
    'Interiors',
    'fridge',
    [0.7, 1.85, 0.7],
    '#c2c4bf',
  ),
  asset('stove', 'Stove', 'Interiors', 'stove', [0.6, 0.9, 0.6], '#a8acac'),
  asset('sink', 'Sink', 'Interiors', 'sink', [0.6, 0.85, 0.5], '#b6bdbe'),
  asset('bathtub', 'Bathtub', 'Interiors', 'tub', [0.8, 0.6, 1.7], '#d9d7ce'),
  asset(
    'fireplace',
    'Fireplace',
    'Interiors',
    'fireplace',
    [1.4, 1.3, 0.4],
    '#968d80',
  ),
  asset('piano', 'Piano', 'Interiors', 'piano', [1.5, 1.2, 0.65], '#65574c'),
  asset(
    'workbench',
    'Workbench',
    'Workshop',
    'desk',
    [1.8, 0.9, 0.7],
    '#9b8569',
  ),
  asset(
    'tool-cabinet',
    'Tool cabinet',
    'Workshop',
    'cabinet',
    [0.8, 1.5, 0.5],
    '#925953',
  ),
  asset(
    'tool-cart',
    'Tool cart',
    'Workshop',
    'cart',
    [0.7, 0.9, 0.45],
    '#a36156',
  ),
  asset(
    'shelving-rack',
    'Storage rack',
    'Workshop',
    'shelf',
    [1.8, 2, 0.6],
    '#8a9498',
  ),
  asset('pallet', 'Pallet', 'Workshop', 'pallet', [1.2, 0.15, 0.8], '#9a815d'),
  asset(
    'oil-drum',
    'Oil drum',
    'Workshop',
    'barrel',
    [0.6, 0.9, 0.6],
    '#74877f',
  ),
  asset(
    'tire-stack',
    'Tire stack',
    'Workshop',
    'tires',
    [0.7, 0.9, 0.7],
    '#3b3e40',
  ),
  asset('ladder', 'Ladder', 'Workshop', 'ladder', [0.5, 2.2, 0.25], '#afb0a5'),
  asset(
    'hangar-door',
    'Hangar door',
    'Workshop',
    'roller',
    [5, 4, 0.2],
    '#8a979c',
  ),
  asset('car-lift', 'Car lift', 'Workshop', 'car-lift', [3.2, 2.2, 1.6], '#b8473d', 'car-lift', 'two post hoist garage'),
  asset('tarp-covered', 'Tarp-covered pile', 'Workshop', 'tarp', [2, 1.1, 1.4], '#5f6f73', 'tarp-covered', 'covered junk sheet'),
  asset('scrap-metal', 'Scrap metal', 'Workshop', 'scrap', [1.4, 0.5, 0.9], '#7d7468', 'scrap-metal', 'junk debris'),
  asset('spare-engine', 'Engine block', 'Workshop', 'engine', [0.7, 0.65, 0.6], '#6b7074', 'spare-engine', 'motor'),
  asset('engine-hoist', 'Engine hoist', 'Workshop', 'hoist', [1, 2, 1.7], '#c2512f', 'engine-hoist', 'crane lift'),
  asset('air-compressor', 'Air compressor', 'Workshop', 'compressor', [0.5, 0.75, 1.1], '#b33a33', 'air-compressor'),
  asset('jerry-can', 'Jerry can', 'Workshop', 'jerry-can', [0.18, 0.45, 0.35], '#6b7d45', 'jerry-can', 'fuel petrol'),
  asset('scaffolding', 'Scaffolding', 'Workshop', 'scaffold', [2.5, 2.5, 1.2], '#9da4a8', 'scaffolding'),
  asset('forklift', 'Forklift', 'Vehicles', 'forklift', [1.2, 2.2, 2.6], '#d6a531', 'forklift'),
  asset('oil-stain', 'Floor stain', 'Workshop', 'decal', [0.9, 0.005, 0.65], '#1d1f1f', 'oil-stain', 'puddle mark'),
  asset('toilet', 'Toilet', 'Interiors', 'toilet', [0.4, 0.8, 0.7], '#e4e2dc', 'toilet'),
  asset('washer', 'Washing machine', 'Interiors', 'washer', [0.6, 0.85, 0.6], '#e1e3e2', 'washer', 'laundry'),
  asset('radiator', 'Radiator', 'Interiors', 'radiator', [1, 0.6, 0.1], '#d8d8d2', 'radiator', 'heater'),
  asset('coat-rack', 'Coat rack', 'Interiors', 'coat-rack', [0.5, 1.8, 0.5], '#7b5b43', 'coat-rack'),
  asset('picture-frame', 'Picture frame', 'Props', 'frame', [0.7, 0.5, 0.04], '#8a6b48', 'picture-frame', 'painting art'),
  asset('ramp', 'Ramp', 'Architecture', 'ramp', [1.2, 0.5, 2.4], '#8e8b84', 'ramp', 'slope'),
  asset('stalagmite', 'Stalagmite', 'Nature', 'spike', [0.5, 1.2, 0.5], '#857b6c', 'stalagmite', 'cave rock'),
  asset('crystal', 'Crystal cluster', 'Nature', 'crystal', [0.5, 0.6, 0.5], '#8fb7c9', 'crystal', 'cave gem'),
  asset('car', 'Car', 'Vehicles', 'car', [1.8, 1.45, 4.3], '#83939a'),
  asset('van', 'Van', 'Vehicles', 'van', [2, 2.2, 5], '#b3b5aa'),
  asset('truck', 'Truck', 'Vehicles', 'truck', [2.2, 2.6, 6], '#929b86'),
  asset(
    'motorcycle',
    'Motorcycle',
    'Vehicles',
    'bike',
    [0.7, 1.1, 2.1],
    '#8d8880',
  ),
  asset('bicycle', 'Bicycle', 'Vehicles', 'bike', [0.6, 1.05, 1.8], '#8da1a8'),
  asset('tree', 'Tree', 'Nature', 'tree', [3, 5, 3], '#788c69'),
  asset('tree-palm', 'Palm tree', 'Nature', 'palm', [3, 5, 3], '#789571'),
  asset('bush', 'Bush', 'Nature', 'bush', [1.4, 0.9, 1.2], '#778864'),
  asset('rock', 'Rock', 'Nature', 'rock', [1.5, 0.9, 1.1], '#8c8d85'),
  asset('log', 'Log', 'Nature', 'log', [0.5, 0.5, 2.2], '#8d7253'),
  asset('water', 'Water', 'Nature', 'water', [4, 0.02, 4], '#658e9e'),
  asset('grass', 'Grass patch', 'Nature', 'rug', [3, 0.02, 3], '#708267'),
  asset(
    'camera',
    'Camera on tripod',
    'Equipment',
    'camera',
    [0.7, 1.6, 0.7],
    '#626e7a',
  ),
  asset(
    'boom-mic',
    'Boom microphone',
    'Equipment',
    'boom',
    [2, 2.5, 0.4],
    '#65727b',
  ),
  asset('c-stand', 'C-stand', 'Equipment', 'stand', [0.7, 2.2, 0.7], '#a3acaf'),
  asset(
    'backdrop',
    'Backdrop',
    'Equipment',
    'board',
    [3, 2.8, 0.12],
    '#b5a999',
  ),
  asset(
    'green-screen',
    'Green screen',
    'Equipment',
    'board',
    [3, 2.8, 0.12],
    '#538b5d',
  ),
];

export const emitsLight = (a?: PrevisAsset) => !!a?.light;

export const assetById = new Map(previsAssets.map((a) => [a.id, a]));
export const assetCategories = [
  ...new Set(previsAssets.map((a) => a.category)),
];

const aliases: Record<string, string> = {
  'actor-female': 'actor-male',
  extra: 'actor-male',
  director: 'actor-male',
  stunt: 'walking-actor',
  'group-small': 'actor-male',
  'group-large': 'actor-male',
  'wall-short': 'wall',
  'wall-corner': 'wall',
  'interior-wall': 'wall',
  'cave-wall-curved': 'cave-wall',
  doorframe: 'archway',
  'roller-door': 'hangar-door',
  'stairs-indoor': 'stairs',
  'dining-table': 'table-rect',
  'kitchen-table': 'table-rect',
  'tv-stand': 'cabinet',
  'shoe-rack': 'bookshelf',
  closet: 'wardrobe',
  mat: 'rug',
  'curtain-window': 'curtain',
  'fill-light': 'softbox',
  'back-light': 'fresnel',
  spotlight: 'dedo',
  'workshop-light': 'led-panel',
  'ceiling-light': 'pendant',
  diffusion: 'diffusion-frame',
  'torch-wall': 'torch-standing',
  'camera-dolly': 'camera',
  'camera-crane': 'camera',
  'camera-handheld': 'camera',
  'camera-steadicam': 'camera',
  'camera-drone': 'camera',
  tripod: 'c-stand',
  monitor: 'screen-tv',
  'car-wreck': 'car',
  boulder: 'rock',
  'boulder-small': 'rock',
  'rock-pile': 'rock',
  'junk-pile': 'scrap-metal',
  painting: 'picture-frame',

  'cave-pool': 'water',
  stream: 'water',
  'floor-area': 'rug',
};
// Named fixtures in a plan often say what they really are.
const labelHints: [RegExp, string][] = [
  [/lyssabel|astera|titan|pavo|tube|light ?stick|rod/i, 'light-tube'],
  [/sky ?panel|s60|s30/i, 'skypanel'],
  [/kino/i, 'kino'],
  [/\bhmi\b|m18|m40/i, 'hmi'],
  [/fresnel|650|\b1k\b|\b2k\b/i, 'fresnel'],
  [/dedo/i, 'dedo'],
  [/china ?ball|lantern/i, 'china-ball'],
];
export function assetForDiagram(
  type: string,
  category: string,
  label = '',
): PrevisAsset | undefined {
  if (category === 'lighting') {
    const hint = labelHints.find(([pattern]) => pattern.test(label));
    if (hint) return assetById.get(hint[1]);
  }
  const exact = assetById.get(aliases[type] ?? type);
  if (exact) return exact;
  if (['text', 'markers', 'shapes'].includes(category)) return undefined;
  if (category === 'characters') return assetById.get('actor-male');
  if (category === 'lighting') return assetById.get('key-light');
  // Unknown physical elements remain editable stand-ins rather than silently disappearing.
  return asset(
    'placeholder',
    'Stand-in',
    'Props',
    'box',
    [0.7, 0.8, 0.7],
    '#9a9d9f',
    type,
  );
}

/** Colour of a black-body source, for dialling a fixture in Kelvin as on set. */
export function kelvinToHex(kelvin: number) {
  const t = Math.min(40000, Math.max(1000, kelvin)) / 100;
  const r = t <= 66 ? 255 : 329.698727446 * Math.pow(t - 60, -0.1332047592);
  const g = t <= 66 ? 99.4708025861 * Math.log(t) - 161.1195681661 : 288.1221695283 * Math.pow(t - 60, -0.0755148492);
  const b = t >= 66 ? 255 : t <= 19 ? 0 : 138.5177312231 * Math.log(t - 10) - 305.0447927307;
  const hex = (n: number) => Math.round(Math.min(255, Math.max(0, n))).toString(16).padStart(2, '0');
  return `#${hex(r)}${hex(g)}${hex(b)}`;
}
